[versions]
agp = "8.3.0-alpha14"
androidx-hilt-navigation-compose = "1.1.0"
androidx-lifecycle-viewmodel-compose = "2.6.2"
androidx-room-compiler = "2.6.0"
androidx-room-ktx = "2.6.0"
androidx-room-runtime = "2.6.0"
hilt-android = "2.48.1"
kotlin = "1.9.20"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.2"
activity-compose = "1.8.1"
compose-bom = "2023.10.01"
google-services = "4.4.0"
coil-compose = "2.4.0"


firebase-storage-ktx = "20.3.0"
navigation-compose = "2.7.5"

ksp = "1.9.20-1.0.14"

[libraries]
androidx-hilt-navigation-compose-v100 = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-lifecycle-viewmodel-compose-v262 = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-viewmodel-compose" }
androidx-room-compiler-v260 = { module = "androidx.room:room-compiler", version.ref = "androidx-room-compiler" }
androidx-room-ktx-v260 = { module = "androidx.room:room-ktx", version.ref = "androidx-room-ktx" }
androidx-room-runtime-v260 = { module = "androidx.room:room-runtime", version.ref = "androidx-room-runtime" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }

firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }

hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

